name: velora
description: "Velora clothes store"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animate_do: ^4.2.0
  build_runner: 2.4.11
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.6
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  # fluttertoast: ^8.2.12
  flutter_zoom_drawer: ^3.2.0
  fluttertoast: ^8.2.12
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.7.1
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  retrofit_generator: ^8.2.1
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  # dart run build_runner build --delete-conflicting-outputs

dev_dependencies:
  connectivity_plus: ^6.1.3
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'assets\images\core\icon.png'
  remove_alpha_ios: true
  min_sdk_android: 21
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.dev
    - .env.prod
    - assets/svg/
    - assets/icons/
    - assets/images/
    - assets/images/core/
    - assets/images/admin/
    - assets/images/customer/
    - lang/ar.json
    - lang/en.json

  fonts:
    - family: Cairo
      fonts:
        - asset: assets\images\fonts\arabic\cairo\Cairo-Bold.ttf
          weight: 700
        - asset: assets\images\fonts\arabic\cairo\Cairo-Medium.ttf
          weight: 500
        - asset: assets\images\fonts\arabic\cairo\Cairo-Regular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets\images\fonts\english\poppins\Poppins-Bold.ttf
          weight: 700
        - asset: assets\images\fonts\english\poppins\Poppins-Medium.ttf
          weight: 500
        - asset: assets\images\fonts\english\poppins\Poppins-Regular.ttf
          weight: 400
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
