// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbga9c2xAu2jRxAsXrEISwLC0aFFfjQD4',
    appId: '1:50540755259:web:06c9f626e3520d2e325f1e',
    messagingSenderId: '50540755259',
    projectId: 'velora-store',
    authDomain: 'velora-store.firebaseapp.com',
    storageBucket: 'velora-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkKdDXyqRIyY8DCzF9UGLBHSymGjOPo0k',
    appId: '1:50540755259:android:89da0a5a735a375c325f1e',
    messagingSenderId: '50540755259',
    projectId: 'velora-store',
    storageBucket: 'velora-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrR1uWh7nGdjvwh8tQM7r77zWy4I5ieI4',
    appId: '1:50540755259:ios:4a2b11a7ce598449325f1e',
    messagingSenderId: '50540755259',
    projectId: 'velora-store',
    storageBucket: 'velora-store.firebasestorage.app',
    iosBundleId: 'com.saqrovic.velora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrR1uWh7nGdjvwh8tQM7r77zWy4I5ieI4',
    appId: '1:50540755259:ios:4a2b11a7ce598449325f1e',
    messagingSenderId: '50540755259',
    projectId: 'velora-store',
    storageBucket: 'velora-store.firebasestorage.app',
    iosBundleId: 'com.saqrovic.velora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbga9c2xAu2jRxAsXrEISwLC0aFFfjQD4',
    appId: '1:50540755259:web:9a17654e152fcb46325f1e',
    messagingSenderId: '50540755259',
    projectId: 'velora-store',
    authDomain: 'velora-store.firebaseapp.com',
    storageBucket: 'velora-store.firebasestorage.app',
  );
}
